// Pure C++ unit tests for src/pymc_proto.h — no Arduino, no MeshCore.
// Build with:  c++ -std=c++17 -Isrc tests/test_pymc_proto.cpp -o tests/test_pymc_proto
// Run    with: ./tests/test_pymc_proto
//
// Golden vectors were generated by tests/mock_modem.py (same algorithm,
// Python reference) and cross-checked against the canonical CCITT test
// string "123456789" → 0x29B1, which proves crc16_ccitt() here matches
// every reference implementation in the wild — and therefore matches
// crc16_ccitt() in pymc_usb/firmware/include/protocol.h byte-for-byte.

#include "../src/pymc_proto.h"

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <vector>

static int g_failures = 0;
static int g_checks   = 0;

#define CHECK(cond, ...) do {                                          \
    g_checks++;                                                        \
    if (!(cond)) {                                                     \
      g_failures++;                                                    \
      std::fprintf(stderr, "FAIL %s:%d: %s\n  ", __FILE__, __LINE__, #cond); \
      std::fprintf(stderr, __VA_ARGS__);                               \
      std::fprintf(stderr, "\n");                                      \
    }                                                                  \
  } while (0)

static std::string hex(const uint8_t* p, size_t n) {
  static const char* H = "0123456789abcdef";
  std::string s; s.reserve(n * 2);
  for (size_t i = 0; i < n; i++) { s.push_back(H[p[i] >> 4]); s.push_back(H[p[i] & 0xF]); }
  return s;
}

static std::vector<uint8_t> from_hex(const char* h) {
  std::vector<uint8_t> v;
  for (size_t i = 0; h[i] && h[i+1]; i += 2) {
    auto hex_nyb = [](char c) -> int {
      if (c >= '0' && c <= '9') return c - '0';
      if (c >= 'a' && c <= 'f') return 10 + c - 'a';
      if (c >= 'A' && c <= 'F') return 10 + c - 'A';
      return 0;
    };
    v.push_back((uint8_t)((hex_nyb(h[i]) << 4) | hex_nyb(h[i+1])));
  }
  return v;
}

// ─── CRC vectors ──────────────────────────────────────────────────────
static void test_crc_vectors() {
  using pymc_proto::crc16_ccitt;
  CHECK(crc16_ccitt(nullptr, 0) == 0xFFFF, "init value");
  const uint8_t cv[] = "123456789";
  CHECK(crc16_ccitt(cv, 9) == 0x29B1, "canonical CCITT-FALSE \"123456789\" → 0x29B1");
  // PING header (CMD=0xFF, LEN=0): CRC over [0xFF, 0x00, 0x00]
  const uint8_t ping_hdr[] = { 0xFF, 0x00, 0x00 };
  CHECK(crc16_ccitt(ping_hdr, 3) == 0x03FF, "PING header CRC");
}

// ─── Frame builder ───────────────────────────────────────────────────
static void test_build_frame_ping() {
  uint8_t out[pymc_proto::MAX_FRAME_SIZE];
  size_t n = pymc_proto::build_frame(pymc_proto::CMD_PING, nullptr, 0, out);
  CHECK(n == 6, "PING frame is 6 bytes (SYNC+CMD+LEN2+CRC2), got %zu", n);
  // Golden: aa ff 00 00 ff 03
  const uint8_t want[] = { 0xAA, 0xFF, 0x00, 0x00, 0xFF, 0x03 };
  CHECK(std::memcmp(out, want, n) == 0, "PING bytes mismatch: got=%s",
        hex(out, n).c_str());
}

static void test_build_frame_set_auto_cad() {
  uint8_t out[pymc_proto::MAX_FRAME_SIZE];
  const uint8_t one = 0x01;
  size_t n = pymc_proto::build_frame(pymc_proto::CMD_SET_AUTO_CAD, &one, 1, out);
  // Golden: aa 4a 01 00 01 e6 a5
  const uint8_t want[] = { 0xAA, 0x4A, 0x01, 0x00, 0x01, 0xE6, 0xA5 };
  CHECK(n == sizeof(want), "SET_AUTO_CAD frame size mismatch: got %zu", n);
  CHECK(std::memcmp(out, want, n) == 0, "SET_AUTO_CAD bytes mismatch: got=%s",
        hex(out, n).c_str());
}

static void test_build_frame_set_config_eu_narrow() {
  // Mirror config.example.json: EU/UK Narrow @ 869.618 MHz / 62.5 kHz / SF8 / CR4-8 /
  // tx_power=22 dBm / syncword=0x0012 / preamble=16. Same fields LinuxTcpRadio
  // assembles in sendConfig() before write.
  pymc_proto::RadioConfig cfg{};
  cfg.freq_hz      = 869618000;
  cfg.bandwidth_hz = 62500;
  cfg.sf           = 8;
  cfg.cr           = 8;
  cfg.power_dbm    = 22;
  cfg.syncword     = 0x0012;
  cfg.preamble_len = 16;
  uint8_t wire[14];
  pymc_proto::serialize_radio_config(cfg, wire);
  // Golden (LE struct dump):
  const uint8_t want_wire[] = {
    0x50, 0x51, 0xd5, 0x33,  // 869618000
    0x24, 0xf4, 0x00, 0x00,  // 62500
    0x08, 0x08, 0x16,        // sf cr pwr
    0x12, 0x00,              // syncword 0x0012 LE
    0x10,                    // preamble 16
  };
  CHECK(std::memcmp(wire, want_wire, 14) == 0,
        "RadioConfig wire layout drift: got=%s", hex(wire, 14).c_str());

  uint8_t frame[pymc_proto::MAX_FRAME_SIZE];
  size_t n = pymc_proto::build_frame(pymc_proto::CMD_SET_CONFIG, wire, 14, frame);
  // Golden whole frame:
  auto want = from_hex("aa100e005051d53324f40000080816120010ec35");
  CHECK(n == want.size(), "SET_CONFIG frame size: got %zu want %zu", n, want.size());
  CHECK(std::memcmp(frame, want.data(), n) == 0,
        "SET_CONFIG bytes mismatch: got=%s want=%s",
        hex(frame, n).c_str(), hex(want.data(), want.size()).c_str());
}

// ─── Parser round-trip ───────────────────────────────────────────────
static void test_parser_round_trip_ping() {
  pymc_proto::FrameParser p;
  uint8_t frame[pymc_proto::MAX_FRAME_SIZE];
  size_t n = pymc_proto::build_frame(pymc_proto::CMD_PING, nullptr, 0, frame);
  bool got_frame = false;
  for (size_t i = 0; i < n; i++) {
    if (p.feed(frame[i])) {
      got_frame = true;
      CHECK(p.cmd == pymc_proto::CMD_PING, "PING parse: cmd=0x%02X", p.cmd);
      CHECK(p.payload_len == 0, "PING parse: len=%u", p.payload_len);
    }
  }
  CHECK(got_frame, "PING parse: never returned true");
}

static void test_parser_round_trip_random_payload() {
  // 7-byte payload picked to exercise both length bytes (LSB nonzero).
  const uint8_t payload[7] = { 0xDE, 0xAD, 0xBE, 0xEF, 0x01, 0x02, 0x03 };
  uint8_t frame[pymc_proto::MAX_FRAME_SIZE];
  size_t n = pymc_proto::build_frame(0x04, payload, sizeof(payload), frame);

  pymc_proto::FrameParser p;
  bool got = false;
  for (size_t i = 0; i < n; i++) {
    if (p.feed(frame[i])) {
      got = true;
      CHECK(p.cmd == 0x04, "cmd=0x%02X", p.cmd);
      CHECK(p.payload_len == 7, "len=%u", p.payload_len);
      CHECK(std::memcmp(p.payload, payload, 7) == 0,
            "payload mismatch: got=%s", hex(p.payload, 7).c_str());
    }
  }
  CHECK(got, "round trip never completed");
}

static void test_parser_skips_garbage_before_sync() {
  pymc_proto::FrameParser p;
  // Garbage bytes followed by a valid PING frame.
  const uint8_t garbage[] = { 0x00, 0x11, 0x22, 0xFE, 0x42 };
  for (uint8_t b : garbage) CHECK(!p.feed(b), "garbage byte should not yield frame");

  uint8_t frame[pymc_proto::MAX_FRAME_SIZE];
  size_t n = pymc_proto::build_frame(pymc_proto::CMD_PING, nullptr, 0, frame);
  bool got = false;
  for (size_t i = 0; i < n; i++) {
    if (p.feed(frame[i])) {
      got = true;
      CHECK(p.cmd == pymc_proto::CMD_PING, "cmd after garbage: 0x%02X", p.cmd);
    }
  }
  CHECK(got, "PING frame after garbage never parsed");
}

static void test_parser_rejects_bad_crc() {
  uint8_t frame[pymc_proto::MAX_FRAME_SIZE];
  size_t n = pymc_proto::build_frame(pymc_proto::CMD_PING, nullptr, 0, frame);
  frame[n - 1] ^= 0xFF;   // corrupt high CRC byte
  pymc_proto::FrameParser p;
  bool got = false;
  for (size_t i = 0; i < n; i++) {
    if (p.feed(frame[i])) got = true;
  }
  CHECK(!got, "corrupt CRC must not yield a 'good frame'");
  CHECK(p.crc_failed, "crc_failed flag should be set after bad CRC");
}

// ─── EVT_RX_PACKET parsing ───────────────────────────────────────────
static void test_parse_rx_packet() {
  // rssi=-55 dBm, snr=12.0 dB (×10=120), sig_rssi=-55 dBm + 3 bytes LoRa data.
  uint8_t payload[] = {
    0xC9, 0xFF,             // rssi=-55 LE
    0x78, 0x00,             // snr_x10=120 LE
    0xC9, 0xFF,             // sig_rssi=-55 LE
    0xAB, 0xCD, 0xEF,       // LoRa data
  };
  pymc_proto::RxPacketMeta meta;
  const uint8_t* data = nullptr;
  int len = pymc_proto::parse_rx_packet(payload, sizeof(payload), meta, data);
  CHECK(len == 3, "data len should be 3, got %d", len);
  CHECK(meta.rssi_dbm == -55, "rssi got %d", meta.rssi_dbm);
  CHECK(meta.snr_x10 == 120, "snr_x10 got %d", meta.snr_x10);
  CHECK(meta.sig_rssi_dbm == -55, "sig_rssi got %d", meta.sig_rssi_dbm);
  CHECK(data && data[0] == 0xAB && data[1] == 0xCD && data[2] == 0xEF,
        "data bytes mismatch");
  // Underflow.
  int err = pymc_proto::parse_rx_packet(payload, 5, meta, data);
  CHECK(err < 0, "short payload should return < 0, got %d", err);
}

// ─── EVT_TX_DONE parsing ─────────────────────────────────────────────
static void test_parse_tx_done() {
  uint8_t p[4] = { 0xE8, 0x03, 0x00, 0x00 };  // 1000 us
  uint32_t airtime = 0;
  CHECK(pymc_proto::parse_tx_done(p, 4, airtime), "tx_done parse OK");
  CHECK(airtime == 1000, "airtime got %u", airtime);
  CHECK(!pymc_proto::parse_tx_done(p, 3, airtime), "short payload should fail");
}

// ─── Airtime math sanity ─────────────────────────────────────────────
static void test_airtime_sanity() {
  // Verify monotonicity: longer payload ⇒ longer airtime at the same SF/BW.
  uint32_t a = pymc_proto::estimate_airtime_ms( 16, 8, 62500, 8, 16);
  uint32_t b = pymc_proto::estimate_airtime_ms(128, 8, 62500, 8, 16);
  CHECK(a > 0 && b > a, "monotonic: 16B=%u 128B=%u", a, b);
  // Invalid args ⇒ 0.
  CHECK(pymc_proto::estimate_airtime_ms(16, 4, 62500, 8, 16) == 0, "sf<5 rejected");
  CHECK(pymc_proto::estimate_airtime_ms(16, 8, 0,     8, 16) == 0, "bw=0 rejected");
  // EU/UK Narrow @ SF8/CR4-8/62.5kHz/preamble 16, ~16B payload — should be on the
  // order of ~150-250 ms. Loose bound just to catch gross regressions; this is
  // the regime MeshCore uses for repeaters.
  uint32_t at = pymc_proto::estimate_airtime_ms(16, 8, 62500, 8, 16);
  CHECK(at >= 100 && at <= 400, "EU/UK Narrow @ SF8 16B airtime ~ms got %u", at);
}

// ─── Packet score sanity ─────────────────────────────────────────────
static void test_packet_score_sanity() {
  // SF8 threshold = -10.0; score(-10, _, _) → 0.
  CHECK(pymc_proto::packet_score(-10.0f, 8, 16) == 0.0f, "at threshold → 0");
  // Score climbs with SNR and clamps at 1.0.
  float s_low  = pymc_proto::packet_score(-5.0f, 8, 16);
  float s_high = pymc_proto::packet_score( 8.0f, 8, 16);
  CHECK(s_low > 0.0f && s_low < s_high, "monotonic in SNR: low=%.3f high=%.3f", s_low, s_high);
  CHECK(s_high <= 1.0f, "clamped at 1.0: got %.3f", s_high);
  // Bad SF.
  CHECK(pymc_proto::packet_score(0.0f, 6, 16) == 0.0f, "sf<7 rejected");
}

// ─── Sizes ───────────────────────────────────────────────────────────
static void test_struct_sizes() {
  static_assert(sizeof(pymc_proto::RadioConfig) == 14, "RadioConfig must be 14B");
  CHECK(pymc_proto::FRAME_OVERHEAD == 6, "frame overhead is 6 bytes");
  CHECK(pymc_proto::MAX_LORA_PAYLOAD == 255, "max LoRa payload");
}

int main() {
  test_crc_vectors();
  test_build_frame_ping();
  test_build_frame_set_auto_cad();
  test_build_frame_set_config_eu_narrow();
  test_parser_round_trip_ping();
  test_parser_round_trip_random_payload();
  test_parser_skips_garbage_before_sync();
  test_parser_rejects_bad_crc();
  test_parse_rx_packet();
  test_parse_tx_done();
  test_airtime_sanity();
  test_packet_score_sanity();
  test_struct_sizes();

  std::printf("\n%d/%d checks passed, %d failures\n",
              g_checks - g_failures, g_checks, g_failures);
  return g_failures == 0 ? 0 : 1;
}
