#!/bin/sh
set -e

case "$1" in
  remove|deconfigure)
    if [ -d /run/systemd/system ]; then
      deb-systemd-invoke stop Meshcore-Linux.service >/dev/null || true
    fi
    ;;
esac

#DEBHELPER#

exit 0
